### ISSUE TITLE
support for --chain-file and --fullchain-file commands to create respective files 

### ISSUE THREAD

**Issue by emahuni** [FiloSottile/mkcert#214]
This program is amazing. However there are these commands I just wish were baked in it. I normally have to make these files manually as they are required in many projects. I think it'd be great if mkCert allowed generation of these files using cli arguments:

```bash
# create chain file
$ cat cert-file.pem > chain.pem
$ cat "$(mkcert -CAROOT)/rootCA.pem" >> chain.pem
# create fullchain file
$ cat cert-file.pem > fullchain.pem
$ cat chain.pem >> fullchain.pem
```

https://community.letsencrypt.org/t/public-and-private-keys/25493/3?u=emahuni

This is how I make these files where needed, but it'd be simple to implement and great to have mkcert do this for us through:

```bash
$ mkcert localhost --chain-file chain.pem --fullchain-file fullchain.pem
```
or also produce them together with the default files (cert and key) based on the domain if these arguments are not specified:

```bash
$ mkcert localhost
```

**Comment by FiloSottile** [comment]
Your commands create fullchain as cert+cert+root, while https://community.letsencrypt.org/t/public-and-private-keys/25493/3?u=emahuni says fullchain is just cert+root. The confusion might be due to the fact that LE certs will have an intremediate root, so fullchain in cert+intermediate+root, while mkcert signs directly from the root.

**Comment by emahuni** [comment]
actually I think you mis-read that. it says:
"fullchain.pem is a concatenation of cert.pem and chain.pem in one file"
which is cert+chain that is similar to cert+cert+root since chain is cert+root.
fullchain is exacly as you said: cert+intermediate+root. The intermediate here is cert. 
"chain.pem contains the intermediate certificate, " + the root at the end.

This is exactly what my commands are doing up there. In fact I have been using them like this and they work without any issues in many programs. Nginx, freeswitch, fusionpbx, php projects, nodejs frameworks etc.

**Comment by FiloSottile** [comment]
> The intermediate from mkcert here is cert

There is no intermediate at all, which is why

* chain = root
* fullchain = cert + chain = cert + root

It's very likely clients will ignore the duplicate certificate if you build cert+cert+root, but I suggest you try cert+root, I am also sure it will also work. If not I'd be curious to know what software that is.

Anyway, I still think that these files are easy enough to put together in the most appropriate way for each case, so mkcert doesn't need the extra options.

**Comment by lonniev** [comment]
Why not make it easy for users if it is easy to do? Add the easy-peasy arguments as proposed:

`mkcert localhost --chain-file chain.pem --fullchain-file fullchain.pem`

How many hours will go wasted as users have to recall the order and debate whether cert+root will do or cert+cert+root is necessary?

**Comment by tyteen4a03** [comment]
+1 - just ran into this issue. Please add the option to save us the headache of figuring out how to put a fullchain together.

**Comment by tyteen4a03** [comment]
+1 - just ran into this issue.

**Comment by retrostyle** [comment]
+1 - reopen

**Comment by aprilahijriyan** [comment]
+1 vote for this
