### ISSUE TITLE
Installed certificate does not show up in Certificate Trust Settings

### ISSUE THREAD

**Issue by Epho** [FiloSottile/mkcert#233]
Related to #47 

I recently installed the latest mkcert and am unable to see the cert in "Certificate Trust Settings". I tried uninstalling, deleting the root, and regenerating, for good measure, but no dice.

![IMG_4EF636D49D4C-1](https://user-images.githubusercontent.com/1441652/72121279-704f6980-330f-11ea-99b6-34e150c53c6d.jpeg)

**Comment by coole106** [comment]
I'm having the same issue. I installed a certificate and it's not showing up here.

**Comment by vlad-dinulescu-idnow** [comment]
Hi, one reason could be that the certificate doesn't have a CN (common name) section.

**Comment by vlad2** [comment]
Hi, one reason could be that the certificate doesn't have the CN (common name) section.

**Comment by suda** [comment]
I think I know what's the problem here. At some point, Apple changed the UI for the cert management so after downloading the certificate you get this:

![CF0AD0CE-09DF-4D70-A8ED-851802EC04FA](https://user-images.githubusercontent.com/25722/92710483-22847880-f358-11ea-9b90-6a06b3bdf04e.jpeg)

And yes, it is in Settings but not where you think. At the top of the menu now there's **Profile Downloaded** option:

![91F882A3-AC48-4B0D-B3DF-A04EE3455EE7](https://user-images.githubusercontent.com/25722/92710735-5495da80-f358-11ea-9e38-a8ab0bec072c.jpeg)

You tap that and you should be presented with the installation dialog:
![C8FC6729-9114-413E-B287-0BA36B0036CD](https://user-images.githubusercontent.com/25722/92710616-3d56ed00-f358-11ea-8ce7-bd8a34208584.jpeg)

After that, it should appear in the **Certificate Trust Settings**:

![A8223F86-ABFB-41F2-8E57-AD5813A91FCA](https://user-images.githubusercontent.com/25722/92711126-a0488400-f358-11ea-94a3-84ee22db577f.jpeg)

Hope this helped :)

**Comment by tysecure** [comment]
After generating the certificate, iOS states, "The authenticity of the profile cannot be verified," and it does not show up in Trust settings. Any ideas? Thanks

**Comment by flyi36** [comment]
https://github.com/FiloSottile
Thank u from me

**Comment by oojacoboo** [comment]
> After generating the certificate, iOS states, "The authenticity of the profile cannot be verified," and it does not show up in Trust settings. I'm using the latest version of macOS Venture and iOS 16. Any ideas? Thanks

I had this issue.  You need to install all the intermediary/root CA "profiles".  That'll be something like `ca.pem`.  When you're self-signing and acting as your own CA, this is what's important since it's the key signing the certificates.

**Comment by AhmedNSidd** [comment]
For what it's worth, I tried downloading all the intermediary certificates and then the root certificate (and tried it the other way around too), and couldn't get the certificates verified for my use case (I was exporting the certificates on my browser using Firefox)

**Comment by oojacoboo** [comment]
Email yourself the CA certificate that you created for yourself, to self-sign.  Then from email, install that on iOS as a "profile".  Then go into it and click to trust it, turning your CA certificated into a trusted root CA.

**Comment by oojacoboo** [comment]
Send the root CA certificate to your iOS device that you created, when self-signing whatever other certificate. Then from email, install that on iOS as a "profile". Then go into it and click to trust it, turning your CA certificated into a trusted root CA.

**Comment by AhmedNSidd** [comment]
I did do exactly what you mentioned Jacob, but the issue I’m running into is that iOS ends up saying the certificate can’t be verified, so even though I can install the certificate, I can’t give it full trust.

Anyway, I think this could potentially have something to do with iOS 18. I found this thread: https://forums.developer.apple.com/forums/thread/764673

**Comment by oojacoboo** [comment]
It needs to be a root CA, so make sure that's the case.  Then, you need to go under your settings and "trust" it.  I recall dealing with the unverified bit, but it was because it wasn't being marked as "trusted".

**Comment by gionapaolini** [comment]
For those that still cannot see their certificate under "Certificate Trust Settings"
In my case the problem was that the certificate had an expiry date too high (it can be max 398 days, as stated [here](https://support.apple.com/en-us/102028))

**Comment by ggitthub** [comment]
I created my own CA certificate on Mac, imported it to an iPad and had the same issue with not seeing it in the "Certificate Trust Settings". Turned out I was importing a .p12 file instead of a .cer file (both are available as export from the Mac Keychain app).

The Configuration Profile under Settings > General > VPN & Device Management looks **absolutely identical** in both cases! BUT it doesn't show up to be trusted in Settings > About > Certificate Trust Settings if the .p12 file was used!

**Comment by philip-lamb** [comment]
> For those that still cannot see their certificate under "Certificate Trust Settings" In my case the problem was that the certificate had an expiry date too high (it can be max 398 days, as stated [here](https://support.apple.com/en-us/102028))

From that page:

> This change will not affect certificates issued from user-added or administrator-added Root CAs.

**Comment by dickison746-ops** [comment]
https://chatgpt.com/canvas/shared/6a0945e80f188191a6008982430bae4b
