### ISSUE TITLE
Did everything but still have warning about certificate

### ISSUE THREAD

**Issue by KostLinux** [FiloSottile/mkcert#279]
I did every step from different websites like here: https://kifarunix.com/how-to-create-self-signed-ssl-certificate-with-mkcert-on-ubuntu-18-04/
or here: https://jonathanbossenger.com/setting-up-trusted-ssl-certificates-for-local-development-using-mkcert-on-ubuntu-18-04-with-apache/
or here: https://linoxide.com/linux-how-to/mkcert-localhost-ssl-certificates-linux/
But i still get warning about certificate...
Is it possible to trust this certificate to whole local subnet like 192.168.0.0/24?

**Comment by polarathene** [comment]
1. `mkcert -install`
2. `mkcert example.localhost 192.168.0.42`
3. Access `example.localhost` that resolves to your server (restart browser if needed)

The only reason I add the IP is for my Android phone to access and use the certificate, since it cannot use the hostname. That would require setting up custom DNS to resolve.

**Comment by FiloSottile** [comment]
We'd need more details on what warnings you get and in what tools to help. If you still need help, please open a new issue with information on your environment, what you did, and where you get the unexpected warnings.
