### ISSUE TITLE
feature request: ability to specify org name

### ISSUE THREAD

**Issue by ldayananda** [FiloSottile/mkcert#81]
Currently the following will use UserAndHostname for certificate subject and Issuer OrganizationalUnit:

https://github.com/FiloSottile/mkcert/blob/fcebdc9845560b3945005932dfc0651ac06d6b98/cert.go#L34-L39

It would be nice to be able to specify a different OrganizationalUnit, maybe with `-org-unit=`

**Comment by adamdecaf** [comment]
I'm not a fan of this. `mkcert` is for local dev certificates.

Can you explain the use-case a bit more? If you need a certificate with real details why not get one from a CA?

**Comment by ldayananda** [comment]
This is more for sharing with a team for a locally run tool. The hostname being tied to a user is awkward, but not a showstopper.

**Comment by FiloSottile** [comment]
mkcert has as few configuration options as possible by design. I don't think we should add one for this. I understand it's not great to have a username in a team root, but in a sense it helps remember that you are trusting whoever generated it with full MitM capabilities (as they might have a copy of the private key).
